### ISSUE TITLE
In mobile category drop down is not showing

### ISSUE THREAD

**Issue by mdsaiffraz** [vinsmglobe/test#9]
while opeing starclinc.com on mobile we can see search bar  on front but it act like a search button and there is no dropdown showing

![Screenshot from 2023-01-25 17-11-12](https://user-images.githubusercontent.com/121232249/214554579-fa5135f3-7935-462f-9d1d-afe1bc9957e6.png)

**Comment by akashdeleader2** [comment]
solved
